title: Chatter Dev Documentation
description: Chatter Dev Documentation
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Chatter Repository: https://github.com/ChadWKirk/Chatter
